### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bahhous** [leekevinyg/react-tag-input#2]
node_modules/reactjs-tag-input/dist/index.js:1
import TagInput from "./TagInput";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.reactjs-tag-input (/Users/dev/react nodejs/redact-reactjs-nextjs-app/.next/server/static/development/pages/orders/create.js:8447:18)
    at __webpack_require__ (/Users/dev/react nodejs/redact-reactjs-nextjs-app/.next/server/static/development/pages/orders/create.js:23:31)
    at Module../pages/orders/create.js (/Users/dev/react nodejs/redact-reactjs-nextjs-app/.next/server/static/development/pages/orders/create.js:6203:76)
    at __webpack_require__ (/Users/dev/react nodejs/redact-reactjs-nextjs-app/.next/server/static/development/pages/orders/create.js:23:31)
    at Object.4 (/Users/dev/react nodejs/redact-reactjs-nextjs-app/.next/server/static/development/pages/orders/create.js:7830:18)
    at __webpack_require__ (/Users/dev/react nodejs/redact-reactjs-nextjs-app/.next/server/static/development/pages/orders/create.js:23:31)
    at /Users/dev/react nodejs/redact-reactjs-nextjs-app/.next/server/static/development/pages/orders/create.js:91:18
    at Object.<anonymous> (/Users/dev/react nodejs/redact-reactjs-nextjs-app/.next/server/static/development/pages/orders/create.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:959:30)

**Comment by leekevinyg** [comment]
Hey @Bahhous! Thanks for submitting an issue :) Usually, the module should be imported with the curly brackets like this: 

```import { TagInput } from 'reactjs-tag-input'```

You can check out an example usage [here.](https://github.com/leekevinyg/react-tag-input#Usage)

Let me know if that helps! If it doesn't, let me know as well and we can dig further into why this is occurring for you.

**Comment by Bahhous** [comment]
It worked @leekevinyg thnks ;)
